### ISSUE TITLE
Chromium: disconnect Breaks Back Button on GitHub

### ISSUE THREAD

**Issue by eik3** [disconnectme/disconnect#299]
When I install disconnect  5.17.0 on Chromium 32.0.1700.107 (Developer Build 32.0.1700.107-0ubuntu0.12.04.1~20140204.866.1) Ubuntu 12.04 and use the tree browser on GitHub, the back button no longer works. The displayed URL in the location bar does change, but the page stays the same and a spinner is being showed on the tab and mouse pointer. As soon as I whitelist GitHub, it works.

**Comment by farsyaz** [comment]
Disconnect me dont use this application
