### ISSUE TITLE
Exception for Yandex CDN

### ISSUE THREAD

**Issue by neoascetic** [disconnectme/disconnect#314]
Disconnect allows sites to load scripts from popular CDNs such as Google. 

However, there is [Yandex CDN](http://api.yandex.ru/jslibs/) which is very popular here in Russia. Because currently disconnects blocks all stuff from Yandex, almost half of russian websites doesn't work for me (I must keep in memory that here an exception for "yandex.st" and must turn off blocking for "Advertising/Yandex" by myself, but this also unblocks all advertising stuff which is bad since I want to unlock only CDN-hosted libraries).

Can you add "yandex.st" to exceptions list please?

**Comment by leonko** [comment]
+1

**Comment by dvp10** [comment]
yes lot of russian sitesdon't work correctly
