### ISSUE TITLE
Disconnect 3.14.0 functionality doesn't work with e10s

### ISSUE THREAD

**Issue by BryanQuigley** [disconnectme/disconnect#340]
Disconnect 3.14.0 functionality doesn't work with Firefox multiprocess (e10s).  The GUI widgets do load, but no content appears to be tracked or blocked.

See more about e10s here:
https://wiki.mozilla.org/Electrolysis
http://arewee10syet.com/

**Comment by fredrikekelund** [comment]
What's the status on this one? e10s is coming up fast in Firefox

**Comment by inspector71** [comment]
Guess might as well uninstall if this extension is going to be consigned to bitrot by e10s.

**Comment by BryanQuigley** [comment]
Marked as supporting Firefox 57 (not out yet) so this is fixed.  Thanks

**Comment by fredrikekelund** [comment]
Thanks, @BryanQuigley! 👍
