### ISSUE TITLE
Disconnect vs. Google Disconnect

### ISSUE THREAD

**Issue by LukeOwncloud** [disconnectme/disconnect#344]
Looking through the available plugins for Firefox I see next:

  - Disconnect
  - Facebook Disconnect
  - Google Disconnect
  - Disconnect Search No Restart
  - Twitter Disconnect 

Do I need them all? Does Disconnect include the others?

**Comment by carbureted** [comment]
[Disconnect](https://addons.mozilla.org/en-us/firefox/addon/disconnect/) wraps the blocking extensions (Facebook, Google, Twitter) and is all you need for blocking requests.

[Disconnect Search](https://addons.mozilla.org/en-us/firefox/addon/disconnect-search/) is an addon that allows you to use our private search service, which lets you get search results from your favorite search engine completely privately.

Also, owncloud is awesome :)

**Comment by LukeOwncloud** [comment]
Perfect, that is just what I thought. I way a little confused, though. Could you add a hint to the plugin descriptions? Something like: "FB, Google, Twitter Disconnect is not required if Disconnect is installed."
