### ISSUE TITLE
Disconnect breaks download links in google inbox

### ISSUE THREAD

**Issue by davidshepherd7** [disconnectme/disconnect#346]
When I have disconnect enabled on [Google inbox](https://inbox.google.com) attachment download buttons don't do anything. When I whitelist the site the buttons work again.

I'm using Firefox 38.0 on Ubuntu 15.04 (but also observed on 14.10).

I'm not too bothered about this being fixed (if it's even possible), but I figured the information will probably be useful for someone.

**Comment by disconnectme** [comment]
Hi David,

Definitely useful and we’ll look into it.  Thanks for the heads-up!

Gus

**Comment by soamaven** [comment]
This is also an issue for me. Firefox 50.1.0

**Comment by bigbgh** [comment]
I am still having this issue in latest version of Chrome. Sometimes the attachment preview does not show in the inbox and when you click to view the attachment it doesn't show and isn't downloadable until you whitelist the site.

It seems that attachments should fall under "content" which is never blocked but it isn't working that way.

Thanks.

**Comment by davidshepherd7** [comment]
Well, inbox is dead now so I guess this can be closed.
