### ISSUE TITLE
Query on how Disconnect compiles the lists

### ISSUE THREAD

**Issue by wesley-tan** [disconnectme/disconnect#393]
Hi! I am an undergraduate doing research on browser fingerprinting. I would like to ask about how Disconnect compiles its blocklists. I understand that it has a mechanism whereby users or people can submit suspicious websites, after which this is reviewed. A few questions follow:

1. How was the original list compiled? Was the list compiled initially by user submissions?
2. How are the user submissions assessed? I understand this may be secretive but what are some pointers as to what are some metrics each website is assessed by before it is placed on the blocklist?

Thank you.

**Comment by disconnectme** [comment]
Thanks for writing in. Please see: https://disconnect.me/trackerproteciton

**Comment by Kravimir** [comment]
> Thanks for writing in. Please see: https://disconnect.me/trackerproteciton

@disconnectme You've got a typo in your link. The "ti" is transposed.

Thanks for this excellent browser extension.
